name: Android CI (debug APK)

on:
  workflow_dispatch: {}   # run manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages (API 30)
        run: |
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      # Generate Gradle wrapper (since your repo doesn't include it yet)
      - name: Generate Gradle Wrapper (6.7.1)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 6.7.1
          arguments: wrapper

      - name: Make wrapper executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: GmScreenTV-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
